import type {
  EnclaveCandidateContractsDocument,
  EnclaveCandidateModuleId,
  EnclaveModuleContract,
} from "./contracts";
import { ENCLAVE_CONTRACT_HASH_RULE, ENCLAVE_CONTRACTS_GENERATED_AT } from "./contracts";

const CANDIDATE_MODULES: readonly EnclaveModuleContract[] = [
  {
    moduleId: "normalize_snapshot",
    moduleLabel: "Snapshot Normalizer",
    currentEntrypoint: "src/normalization/normalizeSnapshot.ts#normalizeSnapshot",
    targetTrustBoundary: "tee_candidate",
    deterministic: true,
    inputs: [
      {
        name: "rawSnapshot",
        type: "LightningSnapshot",
        required: true,
        schemaVersion: "lightning-snapshot-v1",
        sensitivity: "operational_sensitive",
        description: "Raw node telemetry snapshot fetched from LNC.",
      },
    ],
    outputs: [
      {
        name: "normalizedSnapshot",
        type: "NormalizedNodeState",
        required: true,
        schemaVersion: "normalized-node-state-v1",
        sensitivity: "operational_sensitive",
        description: "Deterministic normalized state for scoring and privacy modules.",
      },
      {
        name: "normalizedSnapshotHash",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Canonical SHA-256 hash of normalizedSnapshot.",
      },
    ],
    hashRules: [ENCLAVE_CONTRACT_HASH_RULE],
    notes: [
      "Does not require signing key material.",
      "First enclave candidate to reduce raw-shape leakage across host/runtime boundaries.",
    ],
  },
  {
    moduleId: "privacy_transform",
    moduleLabel: "Privacy Transform",
    currentEntrypoint: "src/privacy/applyPrivacyPolicy.ts#applyPrivacyPolicy",
    targetTrustBoundary: "tee_candidate",
    deterministic: true,
    inputs: [
      {
        name: "normalizedSnapshot",
        type: "NormalizedNodeState",
        required: true,
        schemaVersion: "normalized-node-state-v1",
        sensitivity: "operational_sensitive",
        description: "Normalized state generated by normalize_snapshot.",
      },
      {
        name: "privacyMode",
        type: "PrivacyMode",
        required: true,
        sensitivity: "public",
        description: "Requested privacy mode: full_internal, feature_only, or banded.",
      },
    ],
    outputs: [
      {
        name: "privacyTransformedNodeState",
        type: "PrivacyTransformedNodeState",
        required: true,
        schemaVersion: "privacy-node-state-v1",
        sensitivity: "operational_sensitive",
        description: "Policy-transformed node state intended for downstream consumer scope.",
      },
      {
        name: "privacyOutputHash",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Canonical SHA-256 hash of privacyTransformedNodeState.",
      },
    ],
    hashRules: [ENCLAVE_CONTRACT_HASH_RULE],
    notes: [
      "feature_only and banded outputs are the recommended external-facing privacy products.",
      "Banded mode must not leak direct balances or channel identifiers.",
    ],
  },
  {
    moduleId: "score_node_state",
    moduleLabel: "Deterministic Scoring Engine",
    currentEntrypoint: "src/scoring/scoreNodeState.ts#scoreNodeState",
    targetTrustBoundary: "tee_candidate",
    deterministic: true,
    inputs: [
      {
        name: "normalizedSnapshot",
        type: "NormalizedNodeState",
        required: true,
        schemaVersion: "normalized-node-state-v1",
        sensitivity: "operational_sensitive",
        description: "Normalized state generated by normalize_snapshot.",
      },
    ],
    outputs: [
      {
        name: "recommendation",
        type: "RecommendationSetV1",
        required: true,
        schemaVersion: "recommendation-set-v1",
        sensitivity: "operational_sensitive",
        description: "Deterministic fee/forward recommendation payload.",
      },
      {
        name: "recommendationHash",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Canonical SHA-256 hash of recommendation payload.",
      },
      {
        name: "modelVersion",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Pinned model version identifier emitted by the scoring module.",
      },
    ],
    hashRules: [ENCLAVE_CONTRACT_HASH_RULE],
    notes: [
      "No nondeterministic sources should be introduced in this module.",
      "Model currently pinned to heuristic engine fee-forward-v1.",
    ],
  },
  {
    moduleId: "arb_signer",
    moduleLabel: "ARB Signer",
    currentEntrypoint: "src/arb/buildArb.ts#buildArb",
    targetTrustBoundary: "tee_candidate",
    deterministic: true,
    inputs: [
      {
        name: "recommendation",
        type: "RecommendationSetV1",
        required: true,
        schemaVersion: "recommendation-set-v1",
        sensitivity: "operational_sensitive",
        description: "Scoring output to be signed and packaged as ARB.",
      },
      {
        name: "sourceProvenance",
        type: "SourceProvenanceReceipt",
        required: true,
        schemaVersion: "source-provenance-receipt-v1",
        sensitivity: "public",
        description: "Receipt anchoring raw and normalized snapshot hashes.",
      },
      {
        name: "privacyPolicyId",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Identifier for privacy policy used to produce downstream state.",
      },
      {
        name: "devSigningKey",
        type: "string",
        required: true,
        sensitivity: "secret",
        description: "Signing key material. In production this must be enclave/KMS backed.",
      },
      {
        name: "attestation",
        type: "ArbAttestationEvidence",
        required: false,
        schemaVersion: "arb-attestation-evidence-v1",
        sensitivity: "public",
        description: "Optional enclave attestation evidence embedded into ARB payload.",
      },
      {
        name: "issuedAt",
        type: "string",
        required: false,
        sensitivity: "public",
        description: "Optional override for deterministic issuance time.",
      },
      {
        name: "ttlSeconds",
        type: "number",
        required: false,
        sensitivity: "public",
        description: "Optional ARB time-to-live in seconds.",
      },
    ],
    outputs: [
      {
        name: "arb",
        type: "ArbBundle",
        required: true,
        schemaVersion: "arb-v1",
        sensitivity: "operational_sensitive",
        description: "Signed attested recommendation bundle payload.",
      },
      {
        name: "arbHash",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Canonical SHA-256 hash of full ARB JSON payload.",
      },
      {
        name: "signatureDigest",
        type: "string",
        required: true,
        sensitivity: "public",
        description: "Digest captured in arb.signature.digest for signature verification.",
      },
    ],
    hashRules: [ENCLAVE_CONTRACT_HASH_RULE],
    notes: [
      "This is the highest-value enclave target because it handles signing key material.",
      "Current implementation uses local dev HMAC; production must replace with protected signer.",
    ],
  },
];

export const ENCLAVE_CANDIDATE_IDS = [
  "normalize_snapshot",
  "privacy_transform",
  "score_node_state",
  "arb_signer",
] as const satisfies readonly EnclaveCandidateModuleId[];

export const ENCLAVE_CANDIDATE_MODULE_CONTRACTS = CANDIDATE_MODULES;

export function buildEnclaveCandidateContractsDocument(): EnclaveCandidateContractsDocument {
  return {
    schemaVersion: "enclave-candidate-contracts-v1",
    pipelineId: "props-local-pipeline-v1",
    generatedAt: ENCLAVE_CONTRACTS_GENERATED_AT,
    generationMode: "deterministic",
    candidateModules: [...ENCLAVE_CANDIDATE_MODULE_CONTRACTS],
  };
}
